version: "3.7"

services:
  app:
    image: santonenko/getting-started:latest
    build: .
    ports:
      - 3000:3000
    working_dir: /DevOpsApp
    volumes:
      - ./:/DevOpsApp
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:  